# Generated by Django 4.2.7 on 2023-11-13 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verificationtoken',
            name='expiry_datetime_not_in_past',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token_value',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddConstraint(
            model_name='verificationtoken',
            constraint=models.CheckConstraint(check=models.Q(('expiry_datetime__gte', datetime.datetime(2023, 11, 13, 21, 0, 45, 802437, tzinfo=datetime.timezone.utc))), name='expiry_datetime_not_in_past'),
        ),
    ]
