# Generated by Django 4.2.7 on 2023-11-17 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_verificationtoken_expiry_datetime_not_in_past_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventrsvp',
            name='unique_event_rsvp',
        ),
        migrations.RemoveConstraint(
            model_name='verificationtoken',
            name='expiry_datetime_not_in_past',
        ),
        migrations.RenameField(
            model_name='eventrsvp',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='event_id',
            new_name='event',
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(
                fields=('event', 'attendee_email'), name='unique_event_rsvp'),
        ),
        migrations.AddConstraint(
            model_name='verificationtoken',
            constraint=models.CheckConstraint(check=models.Q(('expiry_datetime__gte', datetime.datetime(
                2023, 11, 17, 18, 1, 21, 283258, tzinfo=datetime.timezone.utc))), name='expiry_datetime_not_in_past'),
        ),
    ]
