services:
  db:
    image: postgres:16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  api:
    build:
      context: ./backend
    ports:
      - '8000:8000'
  web:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - api
