services:
  db:
    image: postgres:16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.local
    depends_on:
      - db
    command: ['./wait-for-it.sh', 'db:5432', '--', 'python', 'manage.py', 'runserver', '0.0.0.0:8000']
  web:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - api
  nginx:
    image: nginx:1.25.3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
