services:
  db:
    image: postgres:16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - '8000:8000'
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.test
    depends_on:
      - db
    command: ['./wait-for-it.sh', 'db:5432', '--', 'pytest']
