# Pull base image
FROM python:3.12-slim

# Set working directory
WORKDIR /backend

# Copy only the necessary files for installation
COPY requirements.txt /backend/

# Install packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy project into container
COPY . /backend

# Expose port
EXPOSE 8000

# Run app.py when container launches
CMD ["pytest"]